COMMAND: JKQC 1sa1fa1tma1am-10.log 1sa1fa1tma1am-11.log 1sa1fa1tma1am-12.log 1sa1fa1tma1am-13.log 1sa1fa1tma1am-14.log 1sa1fa1tma1am-15.log 1sa1fa1tma1am-16.log 1sa1fa1tma1am-17.log 1sa1fa1tma1am-18.log 1sa1fa1tma1am-19.log 1sa1fa1tma1am-1.log 1sa1fa1tma1am-20.log 1sa1fa1tma1am-2.log 1sa1fa1tma1am-3.log 1sa1fa1tma1am-4.log 1sa1fa1tma1am-5.log 1sa1fa1tma1am-6.log 1sa1fa1tma1am-7.log 1sa1fa1tma1am-8.log 1sa1fa1tma1am-9.log -reacted -noexample -out database3DFT.pkl
/home/kubeckaj/ACDB/database_v2/DLPNO_vnw09/Clusteromics-V_AyoubiXX/1sa1fa1tma1am
COMMAND: JKQC 1sa1fa1tma1am-10.log 1sa1fa1tma1am-11.log 1sa1fa1tma1am-12.log 1sa1fa1tma1am-13.log 1sa1fa1tma1am-14.log 1sa1fa1tma1am-15.log 1sa1fa1tma1am-16.log 1sa1fa1tma1am-17.log 1sa1fa1tma1am-18.log 1sa1fa1tma1am-19.log 1sa1fa1tma1am-1.log 1sa1fa1tma1am-20.log 1sa1fa1tma1am-2.log 1sa1fa1tma1am-3.log 1sa1fa1tma1am-4.log 1sa1fa1tma1am-5.log 1sa1fa1tma1am-6.log 1sa1fa1tma1am-7.log 1sa1fa1tma1am-8.log 1sa1fa1tma1am-9.log -reacted -noexample -out database1DLPNO.pkl
Number of files: 20
COMMAND: JKQC database1DLPNO.pkl -ct -gout
/home/kubeckaj/ACDB/database_v2/DLPNO_vnw09/Clusteromics-V_AyoubiXX/1sa1fa1tma1am
/home/kubeckaj/ACDB/database_v2/DLPNO_vnw09/Clusteromics-V_AyoubiXX/1sa1fa1tma1am
/home/kubeckaj/ACDB/database_v2/DLPNO_vnw09/Clusteromics-V_AyoubiXX/1sa1fa1tma1am
/home/kubeckaj/ACDB/database_v2/DLPNO_vnw09/Clusteromics-V_AyoubiXX/1sa1fa1tma1am
COMMAND: JKQC 1sa1fa1tma1am-10.log 1sa1fa1tma1am-11.log 1sa1fa1tma1am-12.log 1sa1fa1tma1am-13.log 1sa1fa1tma1am-14.log 1sa1fa1tma1am-15.log 1sa1fa1tma1am-16.log 1sa1fa1tma1am-17.log 1sa1fa1tma1am-18.log 1sa1fa1tma1am-19.log 1sa1fa1tma1am-1.log 1sa1fa1tma1am-20.log 1sa1fa1tma1am-2.log 1sa1fa1tma1am-3.log 1sa1fa1tma1am-4.log 1sa1fa1tma1am-5.log 1sa1fa1tma1am-6.log 1sa1fa1tma1am-7.log 1sa1fa1tma1am-8.log 1sa1fa1tma1am-9.log -reacted -noexample -out database.pkl
Number of files: 20
/home/kubeckaj/ACDB/database_v2/DLPNO_vnw09/Clusteromics-V_AyoubiXX/1sa1fa1tma1am
COMMAND: JKQC database.pkl -noexample -fc 100 -v 0.996 -sort g -select 3 -reacted -unique rg,el,g -out database3DFT.pkl
sh: /home/kubeckaj/ACDB/database_v2/collect1DLPNO.sh.sh: No such file or directory
COMMAND: JKQC database.pkl -noexample -fc 100 -v 0.996 -globout -reacted -out database1DLPNO.pkl
COMMAND: JKQC database1DLPNO.pkl -ct -gout
/home/kubeckaj/ACDB/database_v2/DLPNO_vnw09/Clusteromics-V_AyoubiXX/1sa1fa1tma1am
COMMAND: JKQC database.pkl -noexample -fc 100 -v 0.996 -sort gout -select 1 -reacted -out database1DLPNO.pkl
Traceback (most recent call last):
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'out'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKQCpickle.py", line 2042, in <module>
    sorted_indices = (clusters_df["log"]["gibbs_free_energy"]-clusters_df["log"]["electronic_energy"]+clusters_df["out"]["electronic_energy"]).sort_values().index
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/frame.py", line 3457, in __getitem__
    return self._getitem_multilevel(key)
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/frame.py", line 3508, in _getitem_multilevel
    loc = self.columns.get_loc(key)
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 2922, in get_loc
    loc = self._get_level_indexer(key, level=0)
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 3204, in _get_level_indexer
    idx = self._get_loc_single_level_index(level_index, key)
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 2855, in _get_loc_single_level_index
    return level_index.get_loc(key)
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'out'
COMMAND: JKQC database1DLPNO.pkl -ct -gout
/home/kubeckaj/ACDB/database_v2/DLPNO_vnw09/Clusteromics-V_AyoubiXX/1sa1fa1tma1am
COMMAND: JKQC database.pkl -noexample -fc 100 -v 0.996 -sort gout -select 1 -reacted -out database1DLPNO.pkl
COMMAND: JKQC database1DLPNO.pkl -ct -gout
