COMMAND: JKQC 2sa3am-10.log 2sa3am-11.log 2sa3am-12.log 2sa3am-13.log 2sa3am-14.log 2sa3am-15.log 2sa3am-16.log 2sa3am-17.log 2sa3am-18.log 2sa3am-19.log 2sa3am-1.log 2sa3am-20.log 2sa3am-21.log 2sa3am-22.log 2sa3am-23.log 2sa3am-24.log 2sa3am-25.log 2sa3am-26.log 2sa3am-27.log 2sa3am-28.log 2sa3am-29.log 2sa3am-2.log 2sa3am-30.log 2sa3am-31.log 2sa3am-32.log 2sa3am-33.log 2sa3am-34.log 2sa3am-35.log 2sa3am-36.log 2sa3am-37.log 2sa3am-38.log 2sa3am-39.log 2sa3am-3.log 2sa3am-40.log 2sa3am-41.log 2sa3am-42.log 2sa3am-43.log 2sa3am-44.log 2sa3am-45.log 2sa3am-46.log 2sa3am-47.log 2sa3am-48.log 2sa3am-49.log 2sa3am-4.log 2sa3am-50.log 2sa3am-5.log 2sa3am-6.log 2sa3am-7.log 2sa3am-8.log 2sa3am-9.log -reacted -noexample -out database.pkl
COMMAND: JKQC database.pkl -ct -gout
/home/kubeckaj/ACDB/database_v2/DLPNO_vnw16/Kubecka23-DFT/SYS_2sa_3am
slurmstepd: error: *** JOB 2640074 ON s95n13 CANCELLED AT 2023-03-08T13:48:21 ***
/home/kubeckaj/ACDB/database_v2/DLPNO_vnw16/Kubecka23-DFT/SYS_2sa_3am
COMMAND: JKQC 2sa3am-10.log 2sa3am-11.log 2sa3am-12.log 2sa3am-13.log 2sa3am-14.log 2sa3am-15.log 2sa3am-16.log 2sa3am-17.log 2sa3am-18.log 2sa3am-19.log 2sa3am-1.log 2sa3am-20.log 2sa3am-21.log 2sa3am-22.log 2sa3am-23.log 2sa3am-24.log 2sa3am-25.log 2sa3am-26.log 2sa3am-27.log 2sa3am-28.log 2sa3am-29.log 2sa3am-2.log 2sa3am-30.log 2sa3am-31.log 2sa3am-32.log 2sa3am-33.log 2sa3am-34.log 2sa3am-35.log 2sa3am-36.log 2sa3am-37.log 2sa3am-38.log 2sa3am-39.log 2sa3am-3.log 2sa3am-40.log 2sa3am-41.log 2sa3am-42.log 2sa3am-43.log 2sa3am-44.log 2sa3am-45.log 2sa3am-46.log 2sa3am-47.log 2sa3am-48.log 2sa3am-49.log 2sa3am-4.log 2sa3am-50.log 2sa3am-5.log 2sa3am-6.log 2sa3am-7.log 2sa3am-8.log 2sa3am-9.log -reacted -noexample -out database1DLPNO.pkl
Number of files: 50
COMMAND: JKQC database1DLPNO.pkl -ct -gout
/home/kubeckaj/ACDB/database_v2/DLPNO_vnw16/Kubecka23-DFT/SYS_2sa_3am
/home/kubeckaj/ACDB/database_v2/DLPNO_vnw16/Kubecka23-DFT/SYS_2sa_3am
COMMAND: JKQC 2sa3am-10.log 2sa3am-11.log 2sa3am-12.log 2sa3am-13.log 2sa3am-14.log 2sa3am-15.log 2sa3am-16.log 2sa3am-17.log 2sa3am-18.log 2sa3am-19.log 2sa3am-1.log 2sa3am-20.log 2sa3am-21.log 2sa3am-22.log 2sa3am-23.log 2sa3am-24.log 2sa3am-25.log 2sa3am-26.log 2sa3am-27.log 2sa3am-28.log 2sa3am-29.log 2sa3am-2.log 2sa3am-30.log 2sa3am-31.log 2sa3am-32.log 2sa3am-33.log 2sa3am-34.log 2sa3am-35.log 2sa3am-36.log 2sa3am-37.log 2sa3am-38.log 2sa3am-39.log 2sa3am-3.log 2sa3am-40.log 2sa3am-41.log 2sa3am-42.log 2sa3am-43.log 2sa3am-44.log 2sa3am-45.log 2sa3am-46.log 2sa3am-47.log 2sa3am-48.log 2sa3am-49.log 2sa3am-4.log 2sa3am-50.log 2sa3am-5.log 2sa3am-6.log 2sa3am-7.log 2sa3am-8.log 2sa3am-9.log -reacted -noexample -out database3DFT.pkl
Number of files: 50
/home/kubeckaj/ACDB/database_v2/DLPNO_vnw16/Kubecka23-DFT/SYS_2sa_3am
/home/kubeckaj/ACDB/database_v2/DLPNO_vnw16/Kubecka23-DFT/SYS_2sa_3am
COMMAND: JKQC 2sa3am-10.log 2sa3am-11.log 2sa3am-12.log 2sa3am-13.log 2sa3am-14.log 2sa3am-15.log 2sa3am-16.log 2sa3am-17.log 2sa3am-18.log 2sa3am-19.log 2sa3am-1.log 2sa3am-20.log 2sa3am-21.log 2sa3am-22.log 2sa3am-23.log 2sa3am-24.log 2sa3am-25.log 2sa3am-26.log 2sa3am-27.log 2sa3am-28.log 2sa3am-29.log 2sa3am-2.log 2sa3am-30.log 2sa3am-31.log 2sa3am-32.log 2sa3am-33.log 2sa3am-34.log 2sa3am-35.log 2sa3am-36.log 2sa3am-37.log 2sa3am-38.log 2sa3am-39.log 2sa3am-3.log 2sa3am-40.log 2sa3am-41.log 2sa3am-42.log 2sa3am-43.log 2sa3am-44.log 2sa3am-45.log 2sa3am-46.log 2sa3am-47.log 2sa3am-48.log 2sa3am-49.log 2sa3am-4.log 2sa3am-50.log 2sa3am-5.log 2sa3am-6.log 2sa3am-7.log 2sa3am-8.log 2sa3am-9.log -reacted -noexample -out database.pkl
Number of files: 50
/home/kubeckaj/ACDB/database_v2/DLPNO_vnw16/Kubecka23-DFT/SYS_2sa_3am
COMMAND: JKQC database.pkl -noexample -fc 100 -v 0.996 -sort g -select 3 -reacted -unique rg,el,g -out database3DFT.pkl
COMMAND: JKQC database.pkl -noexample -fc 100 -v 0.996 -globout -reacted -out database1DLPNO.pkl
COMMAND: JKQC database1DLPNO.pkl -ct -gout
/home/kubeckaj/ACDB/database_v2/DLPNO_vnw16/Kubecka23-DFT/SYS_2sa_3am
COMMAND: JKQC database.pkl -noexample -fc 100 -v 0.996 -sort gout -select 1 -reacted -out database1DLPNO.pkl
Traceback (most recent call last):
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'out'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKQCpickle.py", line 2042, in <module>
    sorted_indices = (clusters_df["log"]["gibbs_free_energy"]-clusters_df["log"]["electronic_energy"]+clusters_df["out"]["electronic_energy"]).sort_values().index
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/frame.py", line 3457, in __getitem__
    return self._getitem_multilevel(key)
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/frame.py", line 3508, in _getitem_multilevel
    loc = self.columns.get_loc(key)
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 2922, in get_loc
    loc = self._get_level_indexer(key, level=0)
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 3204, in _get_level_indexer
    idx = self._get_loc_single_level_index(level_index, key)
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 2855, in _get_loc_single_level_index
    return level_index.get_loc(key)
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'out'
COMMAND: JKQC database1DLPNO.pkl -ct -gout
/home/kubeckaj/ACDB/database_v2/DLPNO_vnw16/Kubecka23-DFT/SYS_2sa_3am
COMMAND: JKQC database.pkl -noexample -fc 100 -v 0.996 -sort gout -select 1 -reacted -out database1DLPNO.pkl
COMMAND: JKQC database1DLPNO.pkl -ct -gout
