COMMAND: JKQC 1sa1put.log 1sa2put.log 1sa3put.log 1sa4put.log 2put.log 2sa1put.log 2sa2put.log 2sa3put.log 2sa4put.log 2sa.log 3put.log 3sa1put.log 3sa2put.log 3sa3put.log 3sa4put.log 3sa.log 4put.log 4sa1put.log 4sa2put.log 4sa3put.log 4sa4put.log 4sa.log -reacted -noexample -out database.pkl
COMMAND: JKQC database.pkl -ct -gout
COMMAND: JKQC 1sa1put.log 1sa2put.log 1sa3put.log 1sa4put.log 2put.log 2sa1put.log 2sa2put.log 2sa3put.log 2sa4put.log 2sa.log 3put.log 3sa1put.log 3sa2put.log 3sa3put.log 3sa4put.log 3sa.log 4put.log 4sa1put.log 4sa2put.log 4sa3put.log 4sa4put.log 4sa.log -reacted -noexample -out database3DFT.pkl
COMMAND: JKQC 1sa1put.log 1sa2put.log 1sa3put.log 1sa4put.log 2put.log 2sa1put.log 2sa2put.log 2sa3put.log 2sa4put.log 2sa.log 3put.log 3sa1put.log 3sa2put.log 3sa3put.log 3sa4put.log 3sa.log 4put.log 4sa1put.log 4sa2put.log 4sa3put.log 4sa4put.log 4sa.log -reacted -noexample -out database3DFT.pkl
/home/kubeckaj/ACDB/database_v2/DLPNO_vtw16/ACDB/sa_put
COMMAND: JKQC 1sa1put.log 1sa2put.log 1sa3put.log 1sa4put.log 2put.log 2sa1put.log 2sa2put.log 2sa3put.log 2sa4put.log 2sa.log 3put.log 3sa1put.log 3sa2put.log 3sa3put.log 3sa4put.log 3sa.log 4put.log 4sa1put.log 4sa2put.log 4sa3put.log 4sa4put.log 4sa.log -reacted -noexample -out database1DLPNO.pkl
Number of files: 22
COMMAND: JKQC database1DLPNO.pkl -ct -gout
/home/kubeckaj/ACDB/database_v2/DLPNO_vtw16/ACDB/sa_put
/home/kubeckaj/ACDB/database_v2/DLPNO_vtw16/ACDB/sa_put
/home/kubeckaj/ACDB/database_v2/DLPNO_vtw16/ACDB/sa_put
/home/kubeckaj/ACDB/database_v2/DLPNO_vtw16/ACDB/sa_put
COMMAND: JKQC 1sa1put.log 1sa2put.log 1sa3put.log 1sa4put.log 2put.log 2sa1put.log 2sa2put.log 2sa3put.log 2sa4put.log 2sa.log 3put.log 3sa1put.log 3sa2put.log 3sa3put.log 3sa4put.log 3sa.log 4put.log 4sa1put.log 4sa2put.log 4sa3put.log 4sa4put.log 4sa.log -reacted -noexample -out database.pkl
Number of files: 22
/home/kubeckaj/ACDB/database_v2/DLPNO_vtw16/ACDB/sa_put
COMMAND: JKQC 1sa1put.log 1sa2put.log 1sa3put.log 1sa4put.log 2put.log 2sa1put.log 2sa2put.log 2sa3put.log 2sa4put.log 2sa.log 3put.log 3sa1put.log 3sa2put.log 3sa3put.log 3sa4put.log 3sa.log 4put.log 4sa1put.log 4sa2put.log 4sa3put.log 4sa4put.log 4sa.log -reacted -noexample -out database.pkl
COMMAND: JKQC database.pkl -noexample -fc 100 -v 0.996 -sort g -select 3 -reacted -unique rg,el,g -out database3DFT.pkl
COMMAND: JKQC database.pkl -noexample -fc 100 -v 0.996 -globout -reacted -out database1DLPNO.pkl
COMMAND: JKQC database1DLPNO.pkl -ct -gout
/home/kubeckaj/ACDB/database_v2/DLPNO_vtw16/ACDB/sa_put
COMMAND: JKQC database.pkl -noexample -fc 100 -v 0.996 -sort gout -select 1 -reacted -out database1DLPNO.pkl
Traceback (most recent call last):
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'out'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKQCpickle.py", line 2042, in <module>
    sorted_indices = (clusters_df["log"]["gibbs_free_energy"]-clusters_df["log"]["electronic_energy"]+clusters_df["out"]["electronic_energy"]).sort_values().index
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/frame.py", line 3457, in __getitem__
    return self._getitem_multilevel(key)
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/frame.py", line 3508, in _getitem_multilevel
    loc = self.columns.get_loc(key)
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 2922, in get_loc
    loc = self._get_level_indexer(key, level=0)
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 3204, in _get_level_indexer
    idx = self._get_loc_single_level_index(level_index, key)
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 2855, in _get_loc_single_level_index
    return level_index.get_loc(key)
  File "/home/kubeckaj/Applications/JKCS2.1/JKQC/JKCS/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'out'
COMMAND: JKQC database1DLPNO.pkl -ct -gout
/home/kubeckaj/ACDB/database_v2/DLPNO_vtw16/ACDB/sa_put
COMMAND: JKQC database.pkl -noexample -fc 100 -v 0.996 -sort gout -select 1 -reacted -out database1DLPNO.pkl
COMMAND: JKQC database1DLPNO.pkl -ct -gout
COMMAND: JKQC database1DLPNO.pkl -ct -gout -hout -s -fc 100 -v 0.996
COMMAND: JKQC database1DLPNO.pkl -movie
COMMAND: JKQC database1DLPNO.pkl -ct -glob -g -h -s -fc 100 -v 0.996
COMMAND: JKQC database3DFT.pkl -movie
COMMAND: JKQC database1DLPNO.pkl -ct -glob -g -h -s -fc 100 -v 0.996
COMMAND: JKQC database3DFT.pkl -movie
